site_name: AIRS Code Collection
site_url: https://slcs-jsc.github.io/airs/
repo_url: https://github.com/slcs-jsc/airs
docs_dir: manual
theme: material

nav:
    - Home: index.md
    - Links: links.md
