name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: install
      run: sudo apt-get update ; sudo apt-get install gnuplot libgsl-dev libnetcdf-dev libhdf5-dev libhdf4-dev libhdfeos-dev libgctp-dev libnsl-dev libopenmpi-dev openmpi-bin
    - name: build
      run: cd libs ; ./build.sh -airs
    - name: make
      run: cd src ; make STATIC=0
    - name: make check
      run: cd src ; make check
